#!/usr/bin/env python

import sys
import rospy

from zzz_common.params import parse_private_args
from zzz_driver_msgs.msg import ChassisReport, ControlReport
from dbw_mkz_msgs.msg import ThrottleReport, BrakeReport, SteeringReport, GearReport, TurnSignalReport

if __name__ == "__main__":
    rospy.init_node("convert_command")

    # See https://bitbucket.org/DataspeedInc/dbw_mkz_ros/src/default/dbw_mkz_can/src/DbwNode.cpp
    params = parse_private_args(
        input_throttle_topic="throttle_report",
        input_brake_topic="brake_report",
        input_steering_topic="steering_report",
        input_misc_topic="misc_1_report",
        input_wheel_topic="wheel_speed_report",
        input_fuel_topic="fuel_level_report",
        input_surround_topic="surround_report",
        input_driver_assist_topic="driver_assist_report",
        output_chassis_topic="/zzz/drivers/chassis_report",
        output_control_topic="/zzz/drivers/control_report",
        output_auxiliary_topic="/zzz/drivers/aux_report",
        output_resource_topic="/zzz/drivers/res_report",
    )

    # TODO: register subscriber, create buffer and publish in loop
    rospy.spin()
