#!/usr/bin/env python

__module_name__ = "map_provider"

import rospy
import actionlib
from zzz_driver_msgs.msg import MapState, ObstacleDataArray
from geometry_msgs.msg import Pose
from zzz_cognition_dynamic_local_map import DynamicMap

class BuilderNode(object):
    def __init__(self,
        load_action_name="/carla/load_map",
        pose_topic="/carla/environment_perception/ego_vehicle_pose",
        surrounding_vehicle_topic="/carla/environment_perception/vehicle_list",
        map_topic="/carla/local_static_map"):

        self._pose_subscriber = rospy.Subscriber(pose_topic, Pose, self.pose_callback)
        self._surrounding_vehicle_subscriber = rospy.Subscriber(surrounding_vehicle_topic, ObstacleDataArray, self.surrounding_vehicle_callback)
        self._static_map_subscriber = rospy.Subscriber(map_topic, MapState, self.static_map_callback)

        self._map_instance = DynamicMap()

    def static_map_callback(self, msg):
        self._map_instance.update_static_map(msg)

    def pose_callback(self, msg):
        self._map_instance.update_dynamic_map(msg.position.x, msg.position.y)

    def surrounding_vehicle_callback(self, msg):
        self._map_instance.update_vehicle_list(msg.obstacles)

if __name__ == "__main__":

    rospy.init_node("dynamic_map_builder", log_level=rospy.DEBUG)
    node = BuilderNode()
    rospy.spin()
