#!/usr/bin/env python

import rospy
from zzz_common.params import parse_private_args
from zzz_cognition_msgs.msg import MapState

from zzz_planning_decision_continuous_models.path_planner import Path_Planner
from zzz_planning_decision_continuous_models.speed_decision import Speed_Decision
from zzz_planning_decision_continuous_models.learning import RLSPlanner
from zzz_planning_decision_continuous_models import MainDecision

from nav_msgs.msg import Path
from zzz_planning_msgs.msg import DecisionTrajectory
from carla_msgs.msg import CarlaCollisionEvent 

class RLSNode(object):
    def __init__(self):

        params = parse_private_args(
            decision_trajectory_topic="decision_trajectory",
            dynamic_map_topic="/zzz/cognition/local_dynamic_map/map_with_ref",
            collision_topic="/carla/ego_vehicle/collision",
            RVIZ_decision_trajectory_topic="decision_trajectory_path", 
            hz = 20,
        )
        self._rate = rospy.Rate(params.hz)
        model_trajectory = RLSPlanner()
        self._decision_instance = MainDecision(trajectory_planner=model_trajectory)

        # ROS messages
        self._decision_trajectory_publisher = rospy.Publisher(params.decision_trajectory_topic, DecisionTrajectory, queue_size=1)
        self._collision_subscriber = rospy.Subscriber("/carla/ego_vehicle/collision", CarlaCollisionEvent, self.collision_callback)
        self._dynamic_map_subscriber = rospy.Subscriber(params.dynamic_map_topic, MapState, self._decision_instance.receive_dynamic_map)
        self._rviz_decision_trajectory_publisher = rospy.Publisher(params.RVIZ_decision_trajectory_topic, Path, queue_size=1)


    def loop(self):
        while not rospy.is_shutdown():
            # try:
            #     publish_msg = self._decision_instance.update_trajectory()
            # except:
            #     pass
            publish_msg = self._decision_instance.update_trajectory()
            if publish_msg:
                self._decision_trajectory_publisher.publish(publish_msg)
                publish_msg2 = publish_msg.trajectory
                self._rviz_decision_trajectory_publisher.publish(publish_msg2)
                rospy.logdebug("PUBLISH: trajectory length = %d, desired_speed = %f", 
                    len(publish_msg.trajectory.poses), publish_msg.desired_speed)
            self._rate.sleep()


    def collision_callback(self, msg):
        self._decision_instance._path_model_instance._collision_signal = True

if __name__ == "__main__":

    rospy.init_node("rls_node", log_level=rospy.DEBUG)
    node = RLSNode()
    node.loop()

    # rospy.spin()

