# This message provide interface for additional vehicle modules, e.g. ACC, BSD


# Forward Collison Warning status
bool fcw_available
bool fcw_active

# Automatic Emergency Brake status
bool aeb_available
bool aeb_precharge
bool aeb_braking

# Adaptive Cruise Control status
bool acc_available
bool acc_braking

# Lane Departure Warning status
bool ldw_available
bool ldw_left_active
bool ldw_right_active

# Blind Spot Detection status
bool bsd_available
bool bsd_left_active
bool bsd_right_active
