#!/usr/bin/env python
import rospy

from zzz_common.params import parse_private_args
from zzz_perception_msgs.msg import DetectionBoxArray, TrackingBoxArray
from zzz_perception_tracking_object_trackers.trackers import MultiBoxTracker

class TrackingNode:
    def __init__(self):
        params = parse_private_args(
            detection_topic="objects_detected",
            tracking_topic="objects_tracked"
        )

        self._tracker = MultiBoxTracker()
        self._detection_subscriber = rospy.Subscriber(params.detection_topic, DetectionBoxArray, self.detection_callback)
        self._tracking_publisher = rospy.Publisher(params.tracking_topic, TrackingBoxArray, queue_size=1)
        
    def detection_callback(self, msg):
        self._tracker.update(msg)
        self._tracking_publisher.publish(self._tracker.report())

if __name__=="__main__":
    rospy.init_node("box_tracker", log_level=rospy.DEBUG)
    tracker = TrackingNode()
    rospy.spin()