#!/usr/bin/env python

import os
import rospy
import threading

from zzz_common.params import parse_private_args
from zzz_driver_msgs.msg import RigidBodyStateStamped
from zzz_navigation_msgs.msg import Map
from zzz_cognition_msgs.msg import MapState
from zzz_perception_msgs.msg import DetectionBoxArray, TrackingBoxArray
from zzz_cognition_object_locator.obstacle_locator import NearestLocator


class Node(object):
    def __init__(self):
        pass

if __name__ == "__main__":
    rospy.init_node("orthogonal_objects", log_level=rospy.DEBUG)
    node = Node()
    rospy.spin()
