###### option:caffe, onnx, uff ######
gModelType: onnx
###### option:0--FP32, 1--FP16, 2--INT8 ######
gDataType: 1
gMaxBatchSize: 1
gMaxWorkspaceSize: 30  #2^30

gInputNode: [input]
###### caffe model ######
# gCaffePrototxt: ../models/deploy.prototxt
# gCaffeModel: ../models/deploy.caffemodel
# gOutputNode: [deconv0]
# gCnnSeg: True

###### onnx model ######
# gOnnxModel: ../models/part1-0421-nhwc.onnx
# gOutputNode: ["pointpillars_part1/features"]
gOnnxModel: ../models/part2-0421-nhwc.onnx
gOutputNode: ["pointpillars_part2/features"]

###### uff model ######
gUffModel: ../models/