#!/usr/bin/env python

import threading
__module_name__ = "map_provider"

import os
import rospy
import actionlib
from zzz_common.params import parse_private_args
import threading

from geometry_msgs.msg import Pose
from nav_msgs.msg import Path
from zzz_driver_msgs.msg import RigidBodyStateStamped
from zzz_navigation_msgs.msg import Map, MapString
from zzz_navigation_map_provider_sumo import LocalMap

MAP_TYPES = {
    MapString.MAP_UNKNOWN: "unknown",
    MapString.MAP_OPENDRIVE: "opendrive",
    MapString.MAP_SUMO: "sumo"
}

class MapProvider(object):
    def __init__(self):
        params = parse_private_args(
            map_file = "",
            map_input_topic = "static_map", # /zzz/navigation/static_map
            map_output_topic = "local_static_map", # /zzz/navigation/local_static_map
            map_file_type = "opendrive",
            pose_topic = "ego_pose", # /zzz/navigation/ego_pose
            reference_path_topic = "reference_path" # /zzz/navigation/reference_path
        )
        self._map_trigger = threading.Event()
        self._reference_path_trigger = 0

        self._map_instance = LocalMap()
        if os.path.exists(params.map_file):
            if self._map_instance.setup_hdmap(file=params.map_file, mtype=params.map_file_type):
                self._map_trigger.set()

        self._static_map_subscriber = rospy.Subscriber(params.map_input_topic, MapString, self.load_map_callback)
        self._pose_subscriber = rospy.Subscriber(params.pose_topic, RigidBodyStateStamped, self.pose_callback)
        self._reference_path_subscriber = rospy.Subscriber(params.reference_path_topic, Path, self.reference_callback)
        self._local_map_publisher = rospy.Publisher(params.map_output_topic, Map, queue_size=1)

    def load_map_callback(self, map):
        print("++++++ setup_hdmap enter")
        if self._map_instance.setup_hdmap(
            content=map.content, mtype=MAP_TYPES[map.map_type]):
            print("++++++ load_map_callback _map_trigger.set")
            self._map_trigger.set()
        rospy.loginfo("[%s] Map loaded" % __module_name__)
        
    def reference_callback(self, msg):
        print("+++++ reference_callback enter wait ")
        self._map_trigger.wait()
        print("+++++ reference_callback  wait done ")
        if self._map_instance.setup_reference_lane_list(msg):
            print("########## reference_callback set")
            self._reference_path_trigger = 1
        else:
            print("*********self._map_instance.setup_reference_lane_list(msg) - False")
        rospy.loginfo("[%s] Received reference path" % __module_name__)

    def pose_callback(self, msg):
        print("+++++++++++ pose_callback enter wait ##############", msg.state.pose.pose.position.x, msg.state.pose.pose.position.y)
        # Note: Here we actually assume that pose is updating at highest frequency
        #self._reference_path_trigger.wait()
        #jxy: this is where the problem lies. Waiting flnally resulted in time delay!
        print("_reference_path_trigger",self._reference_path_trigger)
        if self._reference_path_trigger:
            print("----------- pose_callback enter wait done ##############")

            new_static_map = self._map_instance.receive_new_pose(msg.state.pose.pose.position.x, msg.state.pose.pose.position.y)
            print("----------- return static map ##############")
            if new_static_map is not None:
                print("---------------publish static map\n\n\n\n\n\n\n\n")
                self._local_map_publisher.publish(new_static_map)

if __name__ == "__main__":
    rospy.init_node("map_provider", log_level=rospy.INFO)
    node = MapProvider()
    rospy.spin()
