#!/usr/bin/env python

import sys
import rospy

from zzz_common.params import parse_private_args

if __name__ == "__main__":
    rospy.init_node("convert_topic")

    params = parse_private_args(
        input_topic="",
        output_topic="",
    )

    if not (params.input_topic and params.output_topic):
        rospy.logerr("Not enought parameters!")
        sys.exit(-1)

    # TODO: register and publish
    
    rospy.spin()
